skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
onchain = "6jsqLJjNynJWc2g1kRNi65wiTCkoUkQ8V3p7MUiBgGgU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
